name: ani_route
description: A lightweight flutter route tool.Provider a simple way to manager routes , direct use dart raw dart params.
version: 0.0.2
homepage: https://github.com/laiiihz/ani_route

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
